dist: focal
language: python
python: 3.7
addons:
        apt:
            packages:
                    - "python3"
                    - "python3-pip" 

install:
        pip3 install --user -r requirements.txt

language: shell
script: source .env && cd gistAPI && python3 gists.py

