dist: trusty
addons:
        apt:
            packages:
                    - "python3"
                    - "python3-pip" 

language: python
python: 3.6
install:
        pip3 install --user -r requirements.txt

language: shell
script: source .env && cd gistAPI && python3 gists.py

